import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, TrendingDown, Loader2, Check, Lock, Download, ChevronDown, ChevronUp } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useState } from "react";
import { api } from "@/api";
import type { Recommendation } from "@/contracts/impactcheck.v2";
import { formatTonnes } from "@/contracts/impactcheck.v2";
import { useProject } from "@/contexts/ProjectContext";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

/* Static metadata for recs by position */
const REC_META = [
  { phase: "operational" as const, confidence: 98, roiMonths: 14 },
  { phase: "embodied"    as const, confidence: 85, roiMonths: 24 },
  { phase: "operational" as const, confidence: 95, roiMonths: 18 },
  { phase: "embodied"    as const, confidence: 92, roiMonths: 36 },
];

function getMeta(idx: number) {
  return REC_META[idx % REC_META.length];
}

function PhasePill({ phase }: { phase: "operational" | "embodied" }) {
  return phase === "operational" ? (
    <span className="text-[9px] font-bold uppercase tracking-widest text-sky-600 bg-sky-100 dark:text-sky-300 dark:bg-sky-900/30 border border-sky-200 dark:border-sky-800 rounded-full px-2.5 py-0.5">
      OPERATIONAL
    </span>
  ) : (
    <span className="text-[9px] font-bold uppercase tracking-widest text-amber-600 bg-amber-100 dark:text-amber-300 dark:bg-amber-900/30 border border-amber-200 dark:border-amber-800 rounded-full px-2.5 py-0.5">
      EMBODIED
    </span>
  );
}

export default function Recommendations() {
  const navigate = useNavigate();
  const { project } = useProject();
  const projectId = project.currentProjectId ?? "prj_1";

  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [generating, setGenerating] = useState(false);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [finalized, setFinalized] = useState(false);
  const [finalizing, setFinalizing] = useState(false);
  const [finalText, setFinalText] = useState<string | null>(null);
  const [phaseFilter, setPhaseFilter] = useState<"all" | "operational" | "embodied">("all");

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const result = await api.generateRecommendations(projectId);
      setRecs(result);
      setExpandedId(null);
      setFinalized(false);
      setFinalText(null);
    } finally {
      setGenerating(false);
    }
  };

  const updateStrategy = (id: string, text: string) => {
    setRecs((prev) => prev.map((r) => (r.id === id ? { ...r, strategyDraftText: text } : r)));
  };

  const handleFinalize = async () => {
    setFinalizing(true);
    try {
      const result = await api.finalizeStrategy(projectId, recs.map((r) => r.id));
      setFinalText(result.strategyText);
      setFinalized(true);
      toast.success("Strategy finalized");
    } finally {
      setFinalizing(false);
    }
  };

  const filteredRecs = recs.filter((_, idx) => {
    if (phaseFilter === "all") return true;
    return getMeta(idx).phase === phaseFilter;
  });

  const totalSavingsKg = recs.reduce((sum, r) => sum + Math.abs(r.expectedDeltaKg), 0);

  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-fade-in-up pb-24">
      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <p className="step-number mb-1">Step 07</p>
          <h1 className="text-2xl font-bold tracking-tight">Reduction Strategies</h1>
          <p className="text-muted-foreground text-sm mt-0.5">Actionable strategies to reduce your carbon footprint.</p>
        </div>
        <div className="flex flex-col items-end gap-2">
          {recs.length > 0 && (
            <div className="flex items-center gap-1.5 flex-wrap justify-end">
              <span className="badge-ai">GENERATED BY IMPACTAI v2.4</span>
              <span className="text-[10px] font-mono text-muted-foreground bg-muted rounded-full px-2.5 py-1 border border-border">
                Total Savings: -{formatTonnes(totalSavingsKg)} t
              </span>
              <span className="text-[10px] font-mono text-muted-foreground bg-muted rounded-full px-2.5 py-1 border border-border">
                Strategies: {recs.length}
              </span>
            </div>
          )}
          {recs.length === 0 && (
            <Button onClick={handleGenerate} disabled={generating} className="gap-2 rounded-xl">
              {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
              Generate Recommendations
            </Button>
          )}
        </div>
      </div>

      {/* Finalized banner */}
      {finalized && finalText && (
        <Card className="card-elevated border-0 overflow-hidden">
          <div className="bg-gradient-green p-5 text-primary-foreground">
            <div className="flex items-center gap-2 mb-2">
              <Lock className="h-4 w-4" />
              <span className="text-sm font-semibold">Strategy Finalized</span>
            </div>
            <p className="text-sm opacity-90">{finalText}</p>
          </div>
        </Card>
      )}

      {/* Filter bar */}
      {recs.length > 0 && (
        <div className="flex items-center gap-2">
          {(["all", "operational", "embodied"] as const).map((f) => (
            <button
              key={f}
              onClick={() => setPhaseFilter(f)}
              className={cn(
                "text-xs font-semibold rounded-full px-4 py-1.5 border transition-all cursor-pointer",
                phaseFilter === f
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-muted text-muted-foreground border-border hover:border-primary/40"
              )}
            >
              {f === "all" ? "All Phases" : f === "operational" ? "Operational" : "Embodied"}
            </button>
          ))}
        </div>
      )}

      {/* Strategy cards */}
      {filteredRecs.map((rec, recIdx) => {
        const idx = recs.indexOf(rec);
        const meta = getMeta(idx);
        const isExpanded = expandedId === rec.id;

        return (
          <Card
            key={rec.id}
            className={cn(
              "card-elevated border-0 transition-all",
              !finalized && "hover:ring-1 hover:ring-primary/20"
            )}
          >
            <CardHeader className="pb-3">
              <div className="flex items-start justify-between gap-3">
                <div className="space-y-1.5 flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <PhasePill phase={meta.phase} />
                    <span className="text-[9px] font-mono font-bold text-muted-foreground border border-border rounded-full px-2 py-0.5">
                      {meta.confidence}% CONFIDENCE
                    </span>
                  </div>
                  <CardTitle className="text-base flex items-center gap-2">
                    <TrendingDown className="h-4 w-4 text-primary shrink-0" />
                    {rec.title}
                  </CardTitle>
                  <p className="text-xs text-muted-foreground">ROI within {meta.roiMonths} months</p>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-xl font-bold font-mono text-primary">
                    -{formatTonnes(Math.abs(rec.expectedDeltaKg))} t
                  </p>
                  <p className="text-[10px] text-muted-foreground">CO₂e reduction</p>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground">{rec.summary}</p>
              {rec.constraints && rec.constraints.length > 0 && (
                <p className="text-[11px] text-muted-foreground/70">⚠ {rec.constraints.join("; ")}</p>
              )}

              {/* View Details toggle */}
              <button
                onClick={() => setExpandedId(isExpanded ? null : rec.id)}
                className="flex items-center gap-1.5 text-xs font-medium text-primary hover:opacity-80 transition-opacity cursor-pointer"
              >
                {isExpanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
                {isExpanded ? "Hide Details" : "View Details"}
              </button>

              {isExpanded && (
                <div className="pt-2 border-t border-border space-y-3">
                  <div className="flex gap-3">
                    <div className="h-7 w-7 rounded-xl bg-primary/15 flex items-center justify-center shrink-0 mt-0.5">
                      <span className="text-[10px] font-bold text-primary">AI</span>
                    </div>
                    <div className="rounded-xl bg-muted/50 p-3 text-sm flex-1">
                      <p className="text-xs text-muted-foreground mb-1 font-semibold">Generated Strategy</p>
                      <p>{rec.summary}</p>
                    </div>
                  </div>
                  {!finalized && (
                    <div className="flex gap-3">
                      <div className="h-7 w-7 rounded-xl bg-accent flex items-center justify-center shrink-0 mt-0.5">
                        <span className="text-[10px] font-bold text-accent-foreground">You</span>
                      </div>
                      <Textarea
                        value={rec.strategyDraftText}
                        onChange={(e) => updateStrategy(rec.id, e.target.value)}
                        className="min-h-[100px] text-sm resize-y rounded-xl flex-1"
                        placeholder="Edit the strategy draft…"
                      />
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        );
      })}

      {/* Finalize button */}
      {recs.length > 0 && !finalized && (
        <Button onClick={handleFinalize} disabled={finalizing} variant="outline" className="w-full gap-2 rounded-xl">
          {finalizing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}
          Finalize Strategy
        </Button>
      )}

      {/* Navigation */}
      <div className="flex justify-between">
        <Button variant="outline" onClick={() => navigate("/report")} className="gap-2 rounded-xl">
          <ArrowLeft className="h-4 w-4" /> Back
        </Button>
      </div>

      {/* Sticky footer */}
      {recs.length > 0 && (
        <div className="fixed bottom-0 inset-x-0 z-30 bg-card/95 backdrop-blur-md border-t border-border md:ml-[272px]">
          <div className="max-w-3xl mx-auto flex items-center justify-between px-5 py-4">
            <div className="flex items-center gap-2">
              <div className="h-2 w-2 rounded-full bg-primary animate-pulse" />
              <span className="text-sm font-semibold text-foreground">
                Audit {finalized ? "Complete (100%)" : "In Progress"}
              </span>
            </div>
            <Button
              onClick={() => navigate("/report")}
              className="gap-2 rounded-xl"
            >
              <Download className="h-4 w-4" /> Download Final Report
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
